services:
  gfc_cdvtools:
    build:
      context: .
    env_file:
      - .env.production
    networks:
      - shared-mongo-net
    restart: unless-stopped

networks:
  shared-mongo-net:
    external: true
